# Generated by Django 4.2.7 on 2024-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Упражнение')),
                ('image', models.ImageField(upload_to='exercises_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'Упражнения',
                'db_table': 'exercises',
            },
        ),
    ]
