# Generated by Django 5.0 on 2024-06-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='memo_items', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Memo-предмет',
                'verbose_name_plural': 'Memo-предметы',
            },
        ),
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Режим')),
            ],
            options={
                'verbose_name': 'Режим',
                'verbose_name_plural': 'Режимы',
            },
        ),
        migrations.CreateModel(
            name='SystemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='sys_img', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Системное изображение',
                'verbose_name_plural': 'Системные изображения',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'тексты',
                'db_table': 'texts',
            },
        ),
        migrations.AddField(
            model_name='exercises',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='templates_folder_name',
            field=models.CharField(default='in-develop-templates', max_length=40, verbose_name='Папка шаблонов'),
        ),
    ]
