# Generated by Django 5.0 on 2024-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_memoitems_modes_systemimages_texts_exercises_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoitems',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='memoitems',
            name='theme',
            field=models.CharField(blank=True, choices=[(1, 'Транспорт'), (2, 'Одежда'), (3, 'Животные'), (4, 'Игрушки'), (5, 'Мебель')], max_length=100, null=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='modes',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='systemimages',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
