# Generated by Django 5.0 on 2024-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_memoitems_level_alter_memoitems_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoitems',
            name='theme',
            field=models.CharField(blank=True, choices=[(1, 'Транспорт'), (2, 'Животные'), (3, 'Путешествие'), (4, 'Природа'), (5, 'Музыка'), (6, 'Мебель'), (7, 'Пейзажи'), (8, 'Одежда')], max_length=100, null=True, verbose_name='Тема'),
        ),
    ]
