# Generated by Django 5.1.1 on 2024-10-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_memoitems_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemimages',
            name='image',
            field=models.ImageField(default='user_placeholder.png', upload_to='sys_img', verbose_name='Изображение'),
        ),
    ]
